### ISSUE TITLE
Python test measures mostly perf of `random.randrange(20)`

### ISSUE THREAD

**Issue by undingen** [pepe78/python-performance#1]
Hi 
I took a quick look at your microbenchmark and noticed that it's mostly not measuring dict performance for CPython and Pyston but instead is spending most of the time in `random.randrange(20)` (and also to a smaller part unicode string concatenation).
Also putting everything into a function and not at the module scope would speed it up a bit.

Not sure how much you like to change the benchmarks between different implementations but just wanted to mention that right now it's not really the dict performance you are seeing.

**Comment by pepe78** [comment]
string concatenation - it is only 50 characters, so I don't think for any language that should be a problem (I am aware of C# StringBuilder, but that should be used for strings over 255 characters).

PyPy - has way better performance than Pyston and CPython and also uses randrange (and is using exactly same script)... So that's not a valid answer either.

Functions should be used when needed.

Your answer does not explain bad performance of Pyston.

**Comment by pepe78** [comment]
And when not using random generator, but following code instead:

c++:
            s += letter[(j+i)%20];

pypy / python / pyston:
        s += letter[(j+i)%20]

Pyston / Python is still at least 10 times slower in comparison with PyPy and even more with C++:

| Language | Adjusted time (s) | Time (s) | CPU (%) | Mem (%) |
|----------|-------------------|----------|---------|---------|
|   c++    |       0.170       |  0.157   |  9.010  |  2.200  |
|   pypy   |       0.417       |  0.403   |  8.624  |  2.200  |
|  pyston  |       4.524       |  4.465   |  8.445  |  2.200  |
| python3  |       8.024       |  7.877   |  8.489  |  2.200  |

**Comment by pepe78** [comment]
I just realized above example generates only 20 strings so it's way faster, but even if you use pseudo random generator instead of random libraries:

c++:
        for(int j=0;j<50;j++)
        {
            x0 = (x0 * a + c) % m;
            s += letter[x0%20];
        }

python:
    for j in range(50):
        x0 = (x0 * a + c) % m
        s += letter[x0%20]

You get again same conclusion, that pyston and python are slow:

| Language | Adjusted time (s) | Time (s) | CPU (%) | Mem (%) |
|----------|-------------------|----------|---------|---------|
|   c++    |       0.401       |  0.306   |  10.898 |  2.200  |
|   pypy   |       0.535       |  0.447   |  9.970  |  2.200  |
|  pyston  |       11.069      |  8.765   |  10.523 |  2.200  |
| python3  |       13.671      |  12.073  |  9.436  |  2.200  |

**Comment by pepe78** [comment]
Just a note for myself here:

    from datetime import datetime
    import random

    dic = {}
    letter = 'qwertyuiopasdfghjklz'

    x0 = 14376
    a = 1664525
    c = 1013904223
    m = 2 ** 32

    for i in range(5000001):
        if i%1000000==0:
            now = datetime.now()
            print(str(now))

        s = ""
        for j in range(50):
            x0 = (x0 * a + c) % m;
            s += letter[x0 % 20]
        dic[s] = True
        
    print(len(dic))

https://en.wikipedia.org/wiki/Linear_congruential_generator
